---
resources:
- name: hello
  type: git
  source:
    uri: https://github.com/yjayaraman-pivotal/concourse-hello
    branch: master
jobs:
- name: unit-test
  plan:
  - get: hello
    trigger: true
  - task: unit-test
    file: hello/concourse/tasks/unit-test.yml
