---
resources:
- name: hello
  type: git
  source:
    uri: {{github-uri}}
    branch: {{github-branch}}
jobs:
- name: unit-test
  serial: true
  plan:
  - get: hello
    trigger: true
  - task: unit-test
    file: hello/concourse/tasks/unit-test.yml
