platform: linux
image_resource:
  type: docker-image
  source:
    repository: stephenreed/jenkins-java8-maven-git
    tag: latest

inputs:
- name: hello

run:
  path: ./hello/concourse/tasks/unit-test.sh
